# Generated by Django 3.1.11 on 2022-08-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Img',
            field=models.ImageField(upload_to='agdum/images/'),
        ),
    ]
