# Generated by Django 4.1 on 2022-08-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20220824_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='array',
            field=models.JSONField(default=''),
        ),
    ]
